### ISSUE TITLE
[IF] Docker 배포 기반 버전 관리

### ISSUE THREAD

**Issue by clghks** [JAVACAFE-STUDY/chainity-docker#11]
- 최신 소스 코드(릴리즈) 반영
  - 새로운 이미지 생성 없이 배포
  - 이미지로 버전 관리

**Comment by rygh4775** [comment]
@clghks 
https://github.com/JAVACAFE-STUDY/community-rewards/pull/265
배포 환경에서 실행시 node_module을 전부 받고 시작하게 설정을 하였으니, 참고해주세요.

**Comment by rygh4775** [comment]
TODO
- Docker 이미지로 버전 관리 (Docker Hub 연동)

**Comment by clghks** [comment]
# Docker Hub 올리기
```zsh
docker tag community-rewards/backend:0.4.0 clghks/community-rewards-backend
docker push clghks/community-rewards-backend:0.4.0
```

# Docker Hub 계정 관련 
- 자바카페 Docker Hub 계정을 하나 만들어야 할 듯 합니다.

**Comment by rygh4775** [comment]
@clghks 네, AWS접속 계정 정보와 동일하게 Docker Hub 계정 만들어주세요

**Comment by rygh4775** [comment]
TODO
- Docker Hub 계정 만들기
  - docker@chainity.co.kr (초대)
- Docker Hub 올리기
  - chainity-api
  - chainity-web
  - chainity-landing
  - chainity-admin
