### ISSUE TITLE
[IF] Host Nginx 설정

### ISSUE THREAD

**Issue by rygh4775** [JAVACAFE-STUDY/chainity-docker#19]
- http -> https
- www.chainity.co.kr -> chainity.co.kr
- chainity.co.kr -> landing (:5000)
- api.chainity.co.kr -> api (:3000)
- ~~*.chainity.co.kr -> web (:8080)~~
  - javacafe.chainity.co.kr -> web (:8080)

**Comment by kioku714** [comment]
@rygh4775 [서버 네트워크 구성도](https://drive.google.com/open?id=1rZ2JJchLP0yYMa2UVV7Tz32vYAVjKypp)에서는 landing이 9090 포트로 되어 있는데 확인 부탁드립니다.

**Comment by rygh4775** [comment]
네 맞아요. landing을 아직 배포를 안한 것으로 알고있어요.
@clghks 배포 혹시 했을까요?

**Comment by kioku714** [comment]
@rygh4775 SSL wild card 가격 조사
- https://www.hosting.kr/servlet/html?pgm_id=XHOSTING045310
- https://sslhosting.gabia.com/service
- https://sectigo.com/products/ssl-certificates-tls/wildcard
